eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true # true 表示自己的IP注册到Eureka Server
server:
  port: 8763
spring:
  application:
    name: service-hi01