eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # true 表示自己的IP注册到Eureka Server
server:
  port: 8762
spring:
  application:
    name: service-hi