server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      my-metadata : ForeverChan
  client:
    service-url:
      defaultZone: http://loclhost:8761/eureka/