server:
  port: 8000

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    root: info


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone:   http://user:password123@localhost:8761/eureka/



feign:
  compression:
    request:
      enabled:  true   # 开启对 request 请求压缩
#      mime-types:
#        - text/xml
#        - application/xml
#        - application/json    # 指定压缩格式
#      min-request-size: 2048  # 压缩的最小阀值，默认 2048，超过2048 （字节） 进行压缩。
#
#    response:
#      enabled:  true  # 开启对 response 的压缩
