eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true # true 表示自己的IP注册到Eureka Server
    # 心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    # 告诉我服务器如果10秒内 未发任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: in

server:
  port: 8762
spring:
  application:
    name: service-hi
logging:
  level:
    com.netfliex: DEBUG
