eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka  # http://localhost:8761/eureka
  instance:
    instance-id: eureka-client-authenticating
    prefer-ip-address: true
server:
  port: 8766
spring:
  application:
    name: service-client