eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: service-feign
feign:
    compression:
        request:
            enabled: false
            mime-types: text/xml,application/xml,application/json
            min-request-size: 1024
        response:
            enabled: false
logging:
  level:
    com.stargis.service.SchedualServiceHi: BASIC #DEBUG BASIC